name: Terraform Validation (Task 5)
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./day5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5
    
    - name: Terraform Init
      run: terraform init -input=false
    
    - name: Terraform Format
      run: terraform fmt -check=true -recursive
    
    - name: Terraform Validate
      run: terraform validate
    
    - name: Terraform Plan (Syntax Only)
      run: terraform plan -input=false -no-color -detailed-exitcode || true
