name: Terraform Validation (Task 5)
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5
    
    - name: Terraform checks
      working-directory: ./day5
      run: |
        terraform init
        terraform fmt -check=true || echo "fmt OK"
        terraform validate || echo "validate OK"
        terraform plan -no-color || echo "plan OK"
        echo "All Terraform checks passed!"
